/*
 * Shush API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shush_api

import (
	"encoding/json"
	"github.com/gorilla/mux"
	log "github.com/sirupsen/logrus"
	"github.com/tivvit/shush/shush/backend"
	"github.com/tivvit/shush/shush/model"
	"io/ioutil"
	"net/http"
	"strconv"
)

func UrlsGet(w http.ResponseWriter, r *http.Request) {
	all, err := bck.GetAll()
	if err != nil {
		log.Error(err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	js, err := json.Marshal(all)
	if err != nil {
		log.Error(err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	_, err = w.Write(js)
	if err != nil {
		log.Warnf("response write failed %s", err.Error())
	}
}

func UrlsPost(w http.ResponseWriter, r *http.Request) {
	url := model.Url{}
	b, err := ioutil.ReadAll(r.Body)
	if err != nil {
		log.Warn("malformed request body", err)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		w.WriteHeader(http.StatusBadRequest)
		_, err = w.Write([]byte(`{"error": "malformed request body"}`))
		if err != nil {
			log.Warnf("response write failed %s", err.Error())
		}
		return
	}
	err = json.Unmarshal(b, &url)
	if err != nil {
		log.Warn("malformed json", err)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		w.WriteHeader(http.StatusBadRequest)
		_, err = w.Write([]byte(`{"error": "malformed json body"}`))
		if err != nil {
			log.Warnf("response write failed %s", err.Error())
		}
		return
	}
	// shortUrl us provided
	if url.ShortUrl != "" {
		// todo inform user
		// todo validate short_url
		err := storeUrl(bck, url.ShortUrl, url)
		if err != nil {
			log.Error(err)
			// todo internal?
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
	} else {
		var shortener string
		shortener = short.Conf.DefaultShortener
		shortenerParam := r.URL.Query().Get("shortener")
		if shortenerParam != "" {
			if _, ok := short.Conf.AllowedShorteners[shortenerParam]; ok {
				shortener = shortenerParam
			}
		}
		var hashAlgo string
		hashAlgo = short.Conf.DefaultHashAlgo
		hashAlgoParam := r.URL.Query().Get("algo")
		if hashAlgoParam != "" {
			if _, ok := short.Conf.AllowedHashAlgo[hashAlgoParam]; ok {
				hashAlgo = hashAlgoParam
			}
		}
		var ln int
		ln = short.Conf.DefaultLen
		lenParamStr := r.URL.Query().Get("len")
		if lenParamStr != "" {
			lenParam, err := strconv.Atoi(lenParamStr)
			if err == nil {
				log.Debug(err)
			} else {
				ln = lenParam
			}
		}
		switch shortener {
		case "generator":
			err := short.Random(&url, ln)
			if err != nil {
				log.Error(err)
				// todo does not have to be internal
				w.WriteHeader(http.StatusInternalServerError)
				return
			}
		case "hash":
			err := short.Hash(&url, hashAlgo, ln)
			if err != nil {
				log.Error(err)
				// todo does not have to be internal
				w.WriteHeader(http.StatusInternalServerError)
				return
			}
		}
	}
	su, err := model.UrlSerialize(url)
	if err != nil {
		log.Error(err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	w.WriteHeader(http.StatusOK)
	_, err = w.Write([]byte(su))
	if err != nil {
		log.Warnf("response write failed %s", err.Error())
	}
}

func UrlsShortUrlDelete(w http.ResponseWriter, r *http.Request) {
	p := mux.Vars(r)
	sUrl := p["short_url"]
	err := bck.Remove(sUrl)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
}

func UrlsShortUrlGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	p := mux.Vars(r)
	sUrl := p["short_url"]
	v, err := bck.GetRaw(sUrl)
	if err != nil {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	w.WriteHeader(http.StatusOK)
	_, err = w.Write([]byte(v))
	if err != nil {
		log.Warnf("response write failed %s", err.Error())
	}
}

func UrlsShortUrlPut(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	p := mux.Vars(r)
	sUrl := p["short_url"]
	url := model.Url{}
	b, err := ioutil.ReadAll(r.Body)
	if err != nil {
		log.Warn("malformed request body", err)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		w.WriteHeader(http.StatusBadRequest)
		_, err = w.Write([]byte(`{"error": "malformed request body"}`))
		if err != nil {
			log.Warnf("response write failed %s", err.Error())
		}
		return
	}
	err = json.Unmarshal(b, &url)
	if err != nil {
		log.Warn("malformed json", err)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		w.WriteHeader(http.StatusBadRequest)
		_, err = w.Write([]byte(`{"error": "malformed json body"}`))
		if err != nil {
			log.Warnf("response write failed %s", err.Error())
		}
		return
	}
	// todo validate struct
	if url.ShortUrl == "" {
		url.ShortUrl = sUrl // todo this is not needed and probably not a great idea
	}
	err = storeUrl(bck, sUrl, url)
	if err != nil {
		log.Error(err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
}

func storeUrl(bck *backend.ShushBackend, sUrl string, url model.Url) error {
	return bck.Set(sUrl, url, url.Expires())
}
