/*
 * Shush API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shush_api
import (
	"time"
)

type Url struct {

	ShortUrl string `json:"short_url"`

	Target string `json:"target"`

	Owners []string `json:"owners"`

	Expiration time.Time `json:"expiration,omitempty"`
}
