/*
 * Shush API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package shush_api

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
	"github.com/tivvit/shush/shush/backend"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route


func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		//handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

var bck *backend.ShushBackend

func SetBackend(b *backend.ShushBackend) {
	bck = b
}

var routes = Routes{
	Route{
		"UrlsGet",
		strings.ToUpper("Get"),
		"/api/v1/urls",
		UrlsGet,
	},

	Route{
		"UrlsPost",
		strings.ToUpper("Post"),
		"/api/v1/urls",
		UrlsPost,
	},

	Route{
		"UrlsShortUrlDelete",
		strings.ToUpper("Delete"),
		"/api/v1/urls/{short_url}",
		UrlsShortUrlDelete,
	},

	Route{
		"UrlsShortUrlGet",
		strings.ToUpper("Get"),
		"/api/v1/urls/{short_url}",
		UrlsShortUrlGet,
	},

	Route{
		"UrlsShortUrlPut",
		strings.ToUpper("Put"),
		"/api/v1/urls/{short_url}",
		UrlsShortUrlPut,
	},
}
